site_name: Informatika Érettségi Python-ul
theme:
  name: 'material'
  feature:
    tabs: true
extra:
  search:
    language: 'hu'
  social:
    - type: 'github'
      link: 'https://github.com/squidfunk'
    - type: 'twitter'
      link: 'https://twitter.com/squidfunk'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/squidfunk'
pages:
- Kezdőlap: 
  - Indulás: index.md
- Rólam:
  - _: about.md
- Érettségi megoldások:
  - 2017 május: 2017_majus.md
  - 2016 május: 2016_majus.md